workflows:
  release-build:
    name: Release Build (iOS & Android)
    environment:
      groups:
        - firebase_credentials
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Show build environment
        script: |
          echo "===== FLUTTER ====="
          flutter --version
          echo "===== XCODE ====="
          xcodebuild -version
          echo "===== COCOAPODS ====="
          pod --version
          echo "===== DART ====="
          dart --version

      - name: Clean and get dependencies
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get

      - name: Create GoogleService-Info.plist
        script: |
          printf '%s\n' "$IOS_FIREBASE_SECRET" > ios/Runner/GoogleService-Info.plist

      - name: Install CocoaPods (dynamic frameworks mặc định)
        script: |
          cd ios
          pod deintegrate
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Verify Bundle ID
        script: |
          /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" ios/Runner/Info.plist

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive
