workflows:
  release-build:
    name: Release Build (iOS)

    environment:
      groups:
        - firebase_credentials

      flutter: 3.47.2
      xcode: 26.4
      cocoapods: 1.16.2

      ios_signing:
        distribution_type: development
        bundle_identifier: com.nguyenquangnam1988vt.location

    scripts:

      - name: Show build environment
        script: |
          echo "===== FLUTTER ====="
          flutter --version

          echo "===== DART ====="
          dart --version

          echo "===== XCODE ====="
          xcodebuild -version

          echo "===== COCOAPODS ====="
          pod --version

      - name: Deep clean
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/ephemeral
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Create GoogleService-Info.plist
        script: |
          echo "$IOS_FIREBASE_SECRET" | base64 --decode > ios/Runner/GoogleService-Info.plist

          test -s ios/Runner/GoogleService-Info.plist

          echo "GoogleService-Info.plist OK"

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Verify Firebase
        script: |
          echo "===== FIREBASE FILE ====="
          ls -lh ios/Runner/GoogleService-Info.plist

          echo "===== FIREBASE BUNDLE ID ====="
          grep -A 1 "BUNDLE_ID" ios/Runner/GoogleService-Info.plist || true

      - name: Verify CocoaPods
        script: |
          echo "===== PODFILE.LOCK ====="
          test -f ios/Podfile.lock
          echo "Podfile.lock OK"

          echo "===== MANIFEST.LOCK ====="
          test -f ios/Pods/Manifest.lock
          echo "Manifest.lock OK"

          echo "===== PATH PROVIDER FOUNDATION ====="
          grep -A 5 -B 2 "path_provider_foundation" ios/Podfile.lock || true

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive
