// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6b31T_Qg4zmHQh1H_DJuOK_3nLyK1YM',
    appId: '1:1028882250122:ios:0d861f33cbb9499c1d7073',
    messagingSenderId: '1028882250122',
    projectId: 'tuantrapc08',
    authDomain: 'tuantrapc08.firebaseapp.com',
    databaseURL: 'https://tuantrapc08-default-rtdb.firebaseio.com',
    storageBucket: 'tuantrapc08.firebasestorage.app',
    measurementId: 'G-XX7HMSVDB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWl-igoiwfP8PWF1Aw0jJQVrX9Q8a_cjw',
    appId: '1:1028882250122:ios:0d861f33cbb9499c1d7073',
    messagingSenderId: '1028882250122',
    projectId: 'tuantrapc08',
    databaseURL: 'https://tuantrapc08-default-rtdb.firebaseio.com',
    storageBucket: 'tuantrapc08.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMezCXsvTRV5c4LejdoYNinseDRoWBt2w',
    appId: '1:1028882250122:ios:0d861f33cbb9499c1d7073',
    messagingSenderId: '1028882250122',
    projectId: 'tuantrapc08',
    databaseURL: 'https://tuantrapc08-default-rtdb.firebaseio.com',
    storageBucket: 'tuantrapc08.firebasestorage.app',
    iosBundleId: 'com.example.app7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu6b31T_Qg4zmHQh1H_DJuOK_3nLyK1YM',
    appId: '1:1028882250122:ios:0d861f33cbb9499c1d7073',
    messagingSenderId: '1028882250122',
    projectId: 'tuantrapc08',
    authDomain: 'tuantrapc08.firebaseapp.com',
    databaseURL: 'https://tuantrapc08-default-rtdb.firebaseio.com',
    storageBucket: 'tuantrapc08.firebasestorage.app',
    measurementId: 'G-H3D3ZV24QT',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMezCXsvTRV5c4LejdoYNinseDRoWBt2w',
    appId: '1:1028882250122:ios:0d861f33cbb9499c1d7073',
    messagingSenderId: '1028882250122',
    projectId: 'tuantrapc08',
    databaseURL: 'https://tuantrapc08-default-rtdb.firebaseio.com',
    storageBucket: 'tuantrapc08.firebasestorage.app',
    iosBundleId: 'com.nguyenquangnam1988vt.location',
  );
}
